#!/usr/bin/env python
# Don't run tests from the root repo dir.
# We want to ensure we're importing from the installed
# binary package not from the CWD.

import os
from subprocess import check_call

_dname = os.path.dirname

sdk_packages = ["halo-third-party-sdk-events"]

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))

for pkg in sdk_packages:
    os.chdir(os.path.join(REPO_ROOT, pkg))
    pip_pkg_name = pkg.replace("-", "_")
    check_call(
        ['nosetests', 'tests', '--with-coverage', '--cover-inclusive', '--cover-erase',
         '--cover-package', pip_pkg_name], shell=True)
